### ISSUE TITLE
elm-lang.org connection and windows debug

### ISSUE THREAD

**Issue by kosir** [rundis/elm-light#10] opened 2016-01-08 12:52 UTC
Hi, sorry to use this as help forum. I probably deleted elm-lang.org connection and I don't know how to add it back (as seen on the video). I can connect to my project, but connection to http://elm-lang-org is not shown. I also miss a lot of docs (I can find just some of them). 
Also, at home I use windows (7 and 10), and debug is not working. At work I use ubuntu and debug is working fine.
I use latest version as for today is 0.3.2. Thanks in advance for any reply.
But I must say that your plugin is beautiful thing, thank you so much!!!

**Comment by kosir** [comment] 2016-01-08 13:29
Oh I figured that out... If I open http://elm-lang.org in browser, this connection is automatically added.
I can also report some other observations: lint on ubuntu just underline text and code completion not working good on ubuntu, also inline docs not working at all on ubuntu with CTRL+D (on windows yes). Can I make a suggestion? It would be more convenient for me if inline docs would work like this: when cursor is on function name -> keyboard shotcut -> open documentation for that function (not inline). 

Next, when I save file and run ELM: View current elm file in browser (elm-reactor) and if page was already opened in browser, browser doesn't refresh page, so I must refresh it manually. It would be great if page would be refreshed.

Again, thank you so much for this plugin!!! It helped me to make my first steps with elm in a simple and user friendly way.

**Comment by rundis** [comment] 2016-01-08 15:35
No worries ! It's not like the issue tracker is swamped with issues. Glad to see that people are using it :-)

Ubuntu:
I just tested on Ubuntu 14,04 with the latest version of the plugin.
- Ref linting: Pls checkout the readme. You need to invoke the command mentioned in 5.1.1 to show error/warning details (with cursor placed somewhere in the range for the underlining)
- Autocomplete  works too (remember it only works when the editor has a connection to project, Typically when you have linted the editor or evaled, showed doc etc). You can see if the editor is connected, by opening the connect bar (open command pane and select "Connect: Show connect bar"). If there is a button called "unset" for your project in the listing shown you the editor is connected). Having said that, as the readme states, the autocomplete feature is incubating. It's not all well behaving (confusing fuzzy matches, overly eager caching of results etc) and I might have to rewrite it to not use the default autocompleter that ships with Light Table.
- Inline docs: Seems to be a problem with searching docs for things that aren't module prefixed. I'll open a separate issue to look into that. I'm using elm oracle for autocompletion and docs, if elm oracle doesn't find docs then nothing is shown (lots of functions have no doc unfortunately).  If you import Debug and write Debug.log somewhere, then place cursor on Debug.log and press ctrl+d does it show something ? It does for me on linux. 
  The inline doc feature is as intended and is sort of the default for how this works across the board in light table. The rationale being that you shouldn't need to loose context. I much prefer this to opening a browser tbh. So it's not likely to change :) but you can always open a separate issue for that, and if others chime in, I can consider adding it as an alternative option.
- Reactor: After save, just press ctrl+r to refresh the browser. Easy peasy ! Pls note though that the inline browser in Light Table seems to be quite aggressive when it comes to caching, so sometimes it doesn't seem to pick up changes in the underlying generated js (atleast if you host your compiled elm js in a separate html file)

Future advice for issue submission:
- Make one issue for each concern
- Provide a prelude (describe the steps you took prior to the bug/issue)

cheers
Magnus

**Comment by rundis** [comment] 2016-01-08 15:55
Sorry. A bit premature to close the issue without giving you a chance to respond :-)

**Comment by kosir** [comment] 2016-01-12 00:58
Thank you for such an exhaustive answer! You can close it now :)
Thanks again for fantastic plugin!

**Closed as completed** 2016-01-12 02:04 UTC

**Comment by mordrax** [comment] 2016-05-20 12:29
I might be a bit late to the show, but since @kosir showed me how to connect to elm-lang again :) here's my auto-browser refresh scripts.

In LT's user.keymap do something like this
`[:editor.elm "ctrl-s" :save :elm-format :clear-console :elm.make-project :elm.lint]` the `elm.make-project` is the one you want. I also lint on save, and clear the console so don't get stale errors.

You need something like this in your elm-package.json:
`"make-info": {"main": "src/main.elm", "out": "dist/js/cotw.js"},`

Then you can just use browser-sync to refresh your browser like this:

```
// I have it in a script dev.sh
elm-reactor &
http-server dist &
browser-sync start --proxy "localhost:8080" --files "dist/js/cotw.js" &
browser-sync start --proxy "localhost:8000" --files "**/*.elm" &
```

This starts the reactor on 8000 and the last line watches elm files and refreshes port 8000 whenever there are changes to any elm files.

It also kicks off a simple http-server serving up a directory (in my case, my dist dir). This has a simple index.html with some external CSS and references my elm.js output. So I watch this file (mine is named cotw.js) and refresh 8080 whenever this file changes.

This means that I can go to localhost:8000 and watch for any compile errors if elm-light or the linter isn't refreshed.
And I can go to localhost:8080 to see my elm script embedded in a webpage.

Hope this helps.
